# Generated by Django 2.2.2 on 2019-06-14 03:19

import cob.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atleta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do atleta')),
            ],
            options={
                'ordering': ('nome',),
            },
        ),
        migrations.CreateModel(
            name='Competicao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da competição')),
                ('condicao_para_vitoria', models.CharField(choices=[('maior', 'Maior_resultado vence'), ('menor', 'Menor resultado vence'), ('maior_de_tres', 'Maior de três resultados vence'), ('menor_de_tres', 'Menor de três resultados vence')], max_length=13, verbose_name='Condição para vitória')),
                ('status', models.CharField(choices=[('aguardando', 'Aguardando início'), ('competindo', 'Competição em andamento'), ('encerrada', 'Competição Encerrada')], default='aguardando', max_length=10, verbose_name='Status da competição')),
            ],
            options={
                'verbose_name': 'competição',
                'verbose_name_plural': 'competições',
                'ordering': ('id',),
            },
            bases=(models.Model, cob.models.BaseModel),
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado', models.DecimalField(decimal_places=3, max_digits=8, verbose_name='Valor do resultado obtido pelo atleta')),
                ('atleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cob.Atleta')),
                ('competicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cob.Competicao')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.AddField(
            model_name='atleta',
            name='competicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cob.Competicao'),
        ),
    ]
